apiVersion: apps/v1
kind: Deployment
metadata:
  name: suienes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suienes
  template:
    metadata:
      labels:
        app: suienes
    spec:
      containers:
      - image: okteto.dev/suienes:latest
        name: suienes
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "5dfc84ba-980e-40a0-9e48-ffed0762da36"
        - name: Vless_Path
          value: "/vl555vs334"
        - name: Vmess_UUID
          value: "5dfc84ba-980e-40a0-9e48-ffed0762da36"
        - name: Vmess_Path
          value: "/vm666vb234"
        - name: Share_Path
          value: "/v2link"
